### PR TITLE
Assign blend_order to styles

### PR DESCRIPTION
**Pull request by tallytalwar**
Styles should be drawn as follows:
1. ground, landuse, roads, buildings, etc.
2. route line
3. labels + icons
4. search results + route icon (app chrome)

where `n+1` is drawn above `n`.

Tested this in eraser-map app.

### CODE REVIEW

**Comment by tallytalwar** [comment]
cc. @nvkelso, Can you have a look at this and merge if this looks good.

This will make sure, route line is drawn below labels and icons, and search results and route icons (icon, start, stop) are drawn above everything else.

**Comment by tallytalwar** [comment]
screenshot_2015-12-16-16-44-43

**Comment by nvkelso** [comment]
Having a look...

**Comment by nvkelso** [comment]
Working for me in app (master-587) for routing. Search is crashing the app so can't confirm there. Time for a drive test :)

**Pull request merged**
