### PR TITLE
Add mz_transit_route_line and mz_station_icon

### PR DESCRIPTION
**Pull request by sarahcodes100**
As part of the new transit ui (https://cloud.githubusercontent.com/assets/6125224/16342811/f4d061c4-3a01-11e6-8ff8-135c62b58471.png), EM needs to be able to draw a polyline for transit stations. It also needs to be able to add a marker for each station. This adds new `layers` `mz_transit_route_line` and `mz_station_icon`

screenshot_20160705-152105

### CODE REVIEW

**Comment by nvkelso** [comment]
Updated a few things:
- Update **`mz_route_line_transit`** (was `mz_transit_route_line`) to be data driven for line color. 
- Update **`mz_route_transit_stop`** (was `mz_transit_stop`) to be clearer about reusing the capital icon.
- Rename **`mz_route_destination`** (was `mz_route_stop`) to disambiguate against transit stop.
- Add two new debug data sources to prove the transit stuff works.
- use UX not UI in the style names and sprite artwork names to better establish a pattern. 
- strip out trailing whitespace (thanks Git)

**Comment by nvkelso** [comment]
Because we're renaming assets, this will be a major version bump.

**Comment by nvkelso** [comment]
Both HTML (CSS) named colors and hex values are allowed on each feature in the transit line data layer:

 screen shot 2016-07-06 at 13 59 34

**Comment by nvkelso** [comment]
@bcamper FYI: example of where we're starting to outgrow our data source & draw syntax both for data visualization and for UX/UI considerations.

**Comment by nvkelso** [comment]
@sarahlensing Please confirm this works in your setup. If so I'll merge this, but requires a new tag and you'll need to update the submodule in your app.

**Comment by sarahcodes100** [comment]
@nvkelso I'm having trouble getting this working. I've update the submodule and am adding a data source with the name `mz_route_line_transit` Can you see anything obvious that I am missing here? https://github.com/mapzen/android/compare/transit-route-lines?expand=1

**Comment by nvkelso** [comment]
@sarahlensing confirmed updates in https://github.com/tangrams/bubble-wrap/pull/184/commits/e9172d25ed9d5aff90c6e94f09b34e4f7755e505 work for her, this is ready to merge, pending version bump for tagging.

**Comment by sarahcodes100** [comment]
@nvkelso yep! the updates are working well

**Pull request merged**
