### PR TITLE
Fix typos in park and school filters

### PR DESCRIPTION
**Pull request by matteblair**

### CODE REVIEW

**Comment by nvkelso** [comment]
Good catch! I think there might be more of these, like for buildings and other landuse tiers?

**Comment by matteblair** [comment]
Could be - I didn't do a thorough search, these just showed up with warnings in tangram-es.

**Comment by nvkelso** [comment]
Looks like these were the only 2 instances.

**Comment by nvkelso** [comment]
Released in https://github.com/tangrams/bubble-wrap/releases/tag/v4.1.1.

**Pull request merged**
