### PR TITLE
Simplify buildings

### PR DESCRIPTION
**Pull request by bcamper**
Remove building duplicate drawing, and reduce number of unique styles by consolidating color calculation logic. To address #16.

Because the diff is difficult to review, here's a walkthrough of the changes:
- Re-structured the draw rules for buildings.
  - Previously there were two layers, `buildings-early` (for footprints) and `buildings` (for extrusions), which caused substantial duplication in drawing of buildings, because it would have been difficult (or at least verbose) to write the rules in such a way as to avoid any overlapping between the two. 
  - Instead, all buildings are now drawn from a single `buildings` layer.
    - This layer first sets up the [default draw properties](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L1880) for building fills and outlines, but sets `visible: false` so that no buildings are actually drawn until activated by later rules.
    - The [`footprints`](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L1898) sub-layer turns on building visibility at different zoom, area, and height thresholds.
    - The [`extrude`](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L1915) sub-layer then further turns on extrusion for a second, more restrictive set of criteria. Because `footprints` and `extrude` are sub-layers of the same ancestor layer, and both set properties on the same `polygons` and `lines` draw groups, they do not cause any duplication or conflict. When only `footprints` rules are met, a regular flat fill is used. When `extrude` criteria is also met, `extrude` properties are turned on.
  - The `extrude` sub-layer also sets the draw groups to draw with different styles: [`building-grid`](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L1927) for the extruded volume, and [`building-line`](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L1932) for the outline. These styles are described below.
  - Landuse-specific properties are then added with [`in_park`](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L1936), `in_university`, etc. A consequence of these rules being consolidated in one layer is that landuse-specific coloring is now used for footprints as well as extrusions, as discussed in #26.
  - No changes to the actual filter criteria for footprints, extrusion, or landuse coloring.
- Building draw styles have been consolidated into a single `building-grid` style.
  - Previously, we had several styles with very slight variations (only for fixed colors), with `buildings_grid` as the base, then customized with styles such as `buildings_grid-parks`, `buildings_grid-hospital`, etc. It's fairly wasteful to compile and draw with many styles that have such slight variation.
  - To consolidate, I first moved the logic for scaling building height into its own style, [`scale-buildings`](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L761). This removed copy-paste redundancy between the old `buildings_grid` and `buildings_lines` styles; the new versions of those styles now each [mix in the `scale-buildings` style](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L776) so the code is shared.
  - The old `buildings_grid` and its derivatives had fixed color values for the roof and walls of each landuse type. To remove the extra derivative styles, I changed the style to use the built-in feature color (set in `layers` draw rules) as the roof color, and used an HSV calculation (modifying the saturation and value of the feature color) to derive the wall color (the [RGB is converted to HSV](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L794), modified, then converted back to RGB for output). By tuning the [HSV params](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L782), I was able to keep the visual very close. We can continue to tweak the color params as well, and if we find the approach too limiting, I have kept the older style derivatives [commented out](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L803). Here's a comparison.
    - **Old (ignore labels):** screen shot 2015-10-03 at 10 28 06 pm **New:** screen shot 2015-10-03 at 10 27 37 pm
    - As with `scale-buildings`, a similar "helper" style was also added for HSV calculations, [`hsv`](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L739). It is mixed into the [`building-grid`](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L776) style.
  - `building-lines`, which is used to draw the outline around the footprint or extruded buildings, now becomes [very concise](https://github.com/tangrams/eraser-map/blob/simplify-buildings/eraser-map.yaml#L831) by reusing styling code from above.

### CODE REVIEW

**Comment by nvkelso** [comment]
I'll have a look at this next week, too much code churn – needs a visual before and after session (or screenshots attached).

**Comment by bcamper** [comment]
It should be almost exactly the same visual, except it adds the building
landuse colors from the extrusions to the footprints as well (because it
was easier to organize that way and @senescape said she was planning to add
them anyway). Should be way more efficient.

Don't let it get too far from master or it will be hard to merge...

**Comment by bcamper** [comment]
Updated the PR description with walkthrough and screenshot side by side.

**Comment by bcamper** [comment]
Updated against the recently rebased style. Visually re-verified changes. Merging to avoid further divergence. Building filter behavior is as described in #16, so should review be reviewed in case we want further tweaks.

**Comment by nvkelso** [comment]
Thank you, looks good :)

**Pull request merged**
