### PR TITLE
Move fonts to scene file and switch to WOFF

### PR DESCRIPTION
**Pull request by bcamper**
This brings the fonts in Bubble Wrap up to par with current Tangram functionality:
- Custom fonts are defined in the `fonts` block in the scene file, so they can work cross-platform in JS and ES without additional logic
- Minor normalization of font `weight` to line up with font definitions (e.g. `weight: normal` instead of `weight: 400`, which is equivalent).
- Switch to WOFF font format (instead of TTF), for smaller files. (WOFF2 is even better, but isn't supported at all on IE11, and while other browsers including Safari and Edge now support it, adoption is not there yet.)
- Special font loading JS code is removed from demo (no longer needed with scene file `fonts`)

However, **do not merge** this yet because it isn't working properly in Tangram ES. The fonts are not loading, getting this error which I think indicates the path is not adding the root scene directory:

```
WARNING fontContext.cpp:330: Local font at path fonts/OpenSans-Light.woff can't be found
WARNING fontContext.cpp:330: Local font at path fonts/OpenSans-Regular.woff can't be found
WARNING fontContext.cpp:330: Local font at path fonts/OpenSans-Italic.woff can't be found
WARNING fontContext.cpp:330: Local font at path fonts/OpenSans-Semibold.woff can't be found
WARNING fontContext.cpp:330: Local font at path fonts/OpenSans-SemiboldItalic.woff can't be found
WARNING fontContext.cpp:330: Local font at path fonts/OpenSans-Bold.woff can't be found
```

There is a related set of errors that I think originate from font loading fallback behavior, these should also be looked at:

```
NOTIFY fontContext.cpp:400: Could not load font file open sans-normalnormal.ttf
NOTIFY fontContext.cpp:400: Could not load font file open sans-normal600.ttf
NOTIFY fontContext.cpp:400: Could not load font file open sans-italicnormal.ttf
NOTIFY fontContext.cpp:400: Could not load font file open sans-normal300.ttf
```

### CODE REVIEW

**Comment by bcamper** [comment]
cc @karimnaaji @tallytalwar on ES font loading issues

**Comment by tallytalwar** [comment]
Reason it fails to find the woff fonts in ES, is because fonts path is not normalized in ES. Pushing a fix for this soon.

**Comment by bcamper** [comment]
@karimnaaji the blocker for this is resolved, right? But is it incorporated into the current Android SDK version yet?

**Comment by tallytalwar** [comment]
@bcamper yup fix for this went in [0.4.3-android](https://github.com/tangrams/tangram-es/releases/tag/0.4.3-android) release of tangram-es. But latest release of android sdk is not using this release.

A new android sdk release using `0.4.3-android` tangram-es release is expected to be done this week.

**Comment by sensescape** [comment]
@tallytalwar Has the new android SDK been released with new Tangram ES to unblock merging the font refactor @bcamper proposed here for Bubble Wrap?

**Pull request merged**
