### PR TITLE
Functions accessing varyings can only be defined in the fragment shader

### PR DESCRIPTION
**Pull request by matteblair**
Fixes https://github.com/tangrams/eraser-map/issues/69 and similar issues on other phones.

### CODE REVIEW

**Comment by tallytalwar** [comment]
Is this defined in glsl spec?

**Comment by matteblair** [comment]
@tallytalwar not that I've found so far. It might be part of the spec, but this is just based on empirical evidence with the drivers we've been able to test.

**Comment by tallytalwar** [comment]
Yup. We gave had a couple of solid evidences showing this behavior.

**Comment by nvkelso** [comment]
Rock it.

**Pull request merged**
