### PR TITLE
Added shields

### PR DESCRIPTION
**Pull request by sensescape**

### CODE REVIEW

**Comment by sensescape** [comment]
This introduces 3 new new font, Montserrat for shields and 2 others for neighborhoods and localities.

But it's not clear if we've done that right, pending #206.

**Comment by nvkelso** [comment]
@sensescape please add font files for the new fonts to the `fonts/` directory and update the `fonts:` section in the YAML (commenting out the web url, adding in the local resource).

**Comment by sensescape** [comment]
@nvkelso Fonts are added and YAML is updated (only 2 new fonts, actually).

**Comment by sensescape** [comment]
Ready to merge!

**Comment by nvkelso** [comment]
LGTM :)

**Pull request merged**
