### PR TITLE
Transit additions to bubble-wrap.yaml

### PR DESCRIPTION
**Pull request by tallytalwar**
- Grabbed all @nvkelso changes from https://github.com/tangrams/bubble-wrap/pull/202 and put it in main bubble-wrap.yaml.
- Also adds sdk_transit_overlay global

### CODE REVIEW

**Comment by tallytalwar** [comment]
transit-4
transit-3
transit-2
transit-1

**Comment by nvkelso** [comment]
LGTM

**Comment by tallytalwar** [comment]
Good to merge?

**Comment by nvkelso** [comment]
Yep

**Pull request merged**
