### PR TITLE
Transform icon sheet to prevent artifacts from transparency blending

### PR DESCRIPTION
**Pull request by matteblair**
Transparent pixels now have RGB values calculated as the average of their non-transparent neighbor pixels.

### CODE REVIEW

**Comment by nvkelso** [comment]
The spritesheet is generated out of Adobe Illustrator. Next time we update it, what process do I need to run to transform the RGB values like you've done in this commit?

**Comment by nvkelso** [comment]
Otherwise looks good.

**Comment by tallytalwar** [comment]
I guess you will have to run the python script @blair1618 posted on slack.

**Comment by matteblair** [comment]
@nvkelso The script is here, with usage comments: 

https://gist.github.com/blair1618/63d7d5459e3edc56aafe

We could track it in git if you prefer.

**Comment by nvkelso** [comment]
Tracking it in the gist for now is fine. Really a sprite artwork repo with the Illustrator file and export JSX file should be created, and the python file would be hosted there, I think?

**Pull request merged**
