### PR TITLE
calculate building tinting in vertex shader

### PR DESCRIPTION
**Pull request by hjanetzek**

### CODE REVIEW

**Comment by nvkelso** [comment]
@bcamper for review as I don't know much about shaders. 

FYI: @sensescape as she owns this bit of code.

**Comment by bcamper** [comment]
Looks right to me and checks out in Tangram Play too. 

@blair1618 can you give a quick look too?

**Comment by matteblair** [comment]
Makes sense to me!

**Comment by nvkelso** [comment]
Preview in Tangram Play matches, LGTM

**Pull request merged**
